name: personal_trainer
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  provider: ^4.0.1

  # Additional UI dependencies used on the APP
  flutter_bloc: ^3.2.0
  curved_navigation_bar: ^0.3.2
  flutter_spinkit: "^4.1.1"
  progress_indicators: ^0.1.4
  argon_buttons_flutter: ^1.0.2
  rounded_loading_button: ^1.0.4
  direct_select: "^1.0.0"
  youtube_player_flutter: ^6.1.0+4
  simple_animations: ^1.3.11
  wave_slider: ^0.2.0
  google_fonts: ^0.3.10
  circular_check_box: ^1.0.1
  step_progress_indicator: ^0.2.1+4 #https://pub.dev/packages/step_progress_indicator#-readme-tab-


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - Images/
  #List of general app Images (Home Screen)
    - Images/AppImage2.jpg
    - Images/AppImage1.jpg
    - Images/AppImage3.jpg
    - Images/AppImage4.jpg
    - Images/AppImage5.jpg
    - Images/AppImage6.jpg
    - Images/AppImage7.jpg
  #List Popular callenges images
    - Images/Challenges/Burpees.jpg
    - Images/Challenges/Fruits.jpg
    - Images/Challenges/Meditation.jpg
    - Images/Challenges/Pushup.jpg
    - Images/Challenges/Water.jpg
  #Emoji List
    - Images/Emoji/Sunglasses.png
    - Images/Emoji/Hurt.png
    - Images/Emoji/Dead.png
   #TrainPreferences
    - Images/TrainPreference/Gym.jpg
    - Images/TrainPreference/Home.jpg
    - Images/TrainPreference/Machine.jpg
    - Images/TrainPreference/Running.jpg
   #Equipment
    - Images/Equipment/Barbell.jpg
    - Images/Equipment/Battle Rope.jpg
    - Images/Equipment/Bench.jpg
    - Images/Equipment/Bike.jpg
    - Images/Equipment/Box.jpg
    - Images/Equipment/Cable Machine.jpg
    - Images/Equipment/Cone.jpg
    - Images/Equipment/Dips Bar.jpg
    - Images/Equipment/Dumbbell.jpg
    - Images/Equipment/Elastic Band.jpg
    - Images/Equipment/Gym Machine.jpg
    - Images/Equipment/Jump Rope.jpg
    - Images/Equipment/Kettlebell.jpg
    - Images/Equipment/Med Ball.jpg
    - Images/Equipment/Mini Band.jpg
    - Images/Equipment/Plate.jpg
    - Images/Equipment/Pullup Bar.jpg
    - Images/Equipment/PVC Pipe.jpg
    - Images/Equipment/Resistance Band.jpg
    - Images/Equipment/Rowing Machine.jpg
    - Images/Equipment/Sandbag.jpg
    - Images/Equipment/Smith Machine.jpg
    - Images/Equipment/Speed Ladder.jpg
    - Images/Equipment/Swiss Ball.jpg
    - Images/Equipment/Treadmill.jpg
    - Images/Equipment/TRX.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
